name: Turbopack Next.js development integration tests

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      diff_base:
        description: >
          The base of the test results to compare against. If not specified,
          will try to compare with latest main branch's test results.
        type: string
        default: 'none'

env:
  NEXT_TEST_SKIP_RETRY_MANIFEST: >-
    ${{ github.workspace }}/integration-test-data/test-results/main/failed-test-path-list.json
  TURBOPACK: 1

jobs:
  # https://github.com/orgs/community/discussions/26671#discussioncomment-4295807
  env-vars:
    runs-on: [self-hosted, linux, x64, metal]
    outputs:
      env_json: ${{ toJson(env) }}
    steps:
      - run: echo "Exposing env vars"

  test-dev:
    name: Next.js integration tests
    uses: ./.github/workflows/integration_tests_reusable.yml
    needs: [env-vars]
    with:
      name: turbopack-development
      test_type: development
      env_json: ${{ needs.env-vars.outputs.env_json }}
      datadog_args: --tags test.type:turbopack.daily --service Turbopack
      diff_base: ${{ inputs.diff_base }}
    secrets: inherit
